### ISSUE TITLE
Create ListAssay to represent Uni-style assets that can be grouped

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/ERTP#101]
This probably makes sense after https://github.com/Agoric/ERTP/pull/100.

I think it will be useful for assets described by unique labels, but that one is allowed to hold multiple assets at a time.

**Comment by katelynsills** [comment]
The pixelList and non-fungible stocks would benefit from using this. We might want to make the ListAssay ordered so that the `with` / `without` / `equals` functions can be more efficient and do better than O(n*2)

**Comment by katelynsills** [comment]
I just pushed up the work I was doing a few weeks ago on an "ordered" pixelList. https://github.com/Agoric/ERTP/tree/ordered-pixelList I think it will be helpful for the ListAssay

**Comment by katelynsills** [comment]
Closed by Agoric/ERTP#116

**Comment by warner** [comment]
in the old repo. this was ERTP issue 101
