### ISSUE TITLE
Support 'near' execution of code provided by remote objects

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/ERTP#102]
Often there is functionality related to a remote object that doesn't need to execute in that obect's home vat. Relying on the remote vat requires extra round trips. When the code doesn't need privileged access, and can keep the information it needs locally, having code provided by the remote module could improve efficiency.

We may eventually be able to make use of Jessie or Justin to provide safe code that clients could execute directly, but there's work to do to enable that.

**Comment by Chris-Hibbert** [comment]
Here's a quick and dirty sketch of something that would be easy to implement, and would be upgradeable to something more robust. It provides an import Manager that imports a collection of files, and then can make objects available by name.

create using
```
  const mgr = importManager();
  mgr.addEntry(uniName, makeUniAssay);
```

lookup using a ```key``` provided by the remote object.
```
  object = mgr.lookupImport(key);
```

========  assayImportManager.js
```
// statically imports files, and makes them available by name.

import { makeUniAssay, name as uniName } from '.../core/uniAssays';
import { makeNatAssay, name as natName } from '.../core/natAssays';
import { makeListAssay, name as listName } from '.../core/listAssay';
import { makePixelListAssay, name as pixelName } from '.../more/pixels/assays';
import importManager from '.../more/imports/manager';

function makeAssayImportManager() {
  const mgr = importManager();
  mgr.addEntry(uniName, makeUniAssay);
  mgr.addEntry(natName, makeNatAssay);
  mgr.addEntry(listName, makeListAssay);
  mgr.addEntry(pixelName, makePixelListAssay);
  mgr.addEntry(uniName, makeUniAssay);
  return mgr;
}

// Later, we intend to manage these using registered names, so we can 
// do version tracking and upgrade. 
```
=========== foo.js
```
import 'makeAssayImportManager' from '.../assayImportManager';

...

  const assayManager = makeAssayImportManager();
  const key = payment.getAssayId();
  const genAssay = assayManager.lookupImport(key);
...
```
===========

**Comment by Chris-Hibbert** [comment]
https://github.com/Agoric/ERTP/pull/105

**Comment by warner** [comment]
in the old repo. this was ERTP issue 102
