### ISSUE TITLE
Use objects as wrapped object capabilities

### ISSUE THREAD

**Issue by katelynsills** [Agoric/ERTP#104]
It occurred to me that what we are calling use objects is generalizable as "wrap this object as an ERTP asset". I'm not sure what role an issuer would play in this generalized version. Is there one issuer for all wrapped objects? One issuer per wrapped object kind? one issuer per wrapped object?

**Comment by Chris-Hibbert** [comment]
So far, we don't have any use objects that are actual objects with behavior. To date, they're all opaque keys that get their behavior by passing them back to something that is holding the mint closely, and recognizes the amounts to take appropriate action. In that model, the assay has to be able to recognize the amounts. 

If we want the wrapped objects to have state and behavior, I think we'd continue to want the assay to be able to vouch() for them. That tells me that the issuer should be as wide as makes sense and still have the ability to recognize the objects as its own.

**Comment by katelynsills** [comment]
I think your description of how use objects work isn't exactly right. Our use objects right now are actual objects with behavior. The objects have an ERTP asset in scope that the object methods check the balance of to get the property authority to continue with the methods. To me, this seems very different than use objects being "opaque keys that get their behavior by passing them back to something." The use objects aren't passed to anything, and they aren't used as opaque keys. The assay doesn't vouch for a use object.  I could be misunderstanding what you meant, though, so please let me know if that's the case. Here's the relevant code from the gallery that creates the use object:

```js
  function makeUseObj(issuer, asset) {
    const useObj = harden({
      // change the color of the pixels in the amount after checking
      // that the asset has the authority to do so.
      changeColor(amount, newColor) {
        // TODO: allow empty amounts to be used without throwing
        // an error, but because there is no authority, nothing happens.
        insistNonEmptyAmount(issuer, amount);
        insistAssetHasAmount(issuer, asset, amount);
        insistColor(newColor);
        const pixelList = getPixelList(issuer, amount);
        setPixelListState(pixelList, newColor);
        return amount;
      },
     ...
```
There are further methods, but `changeColor` is the method that is used the most.  `insistNonEmptyAmount` and `insistAssetHasAmount` are defined as:

```js
  function insistNonEmptyAmount(issuer, amount) {
    insist(!issuer.getAssay().isEmpty(amount))`\
      no use rights present in amount ${amount}`;
  }

  function insistAssetHasAmount(issuer, asset, amount) {
    insist(issuer.getAssay().includes(asset.getBalance(), amount))`\
      ERTP asset ${asset} does not include amount ${amount}`;
  }
```

In this code, the only way that `changeColor` succeeds is if the `asset` passed in at its creation has a balance of some pixels. So it all depends on the balance of the ERTP asset, not anything to do with passing this use object or the assay vouching for this use object.

**Comment by Chris-Hibbert** [comment]
Thanks for the clarification/correction.  

I think the point of the issuer and assay is to be able to validate that the objects have assets of the recognized type. It looks like the use objects don't participate in that conversation, so you have to use the purses and payments for that. If use objects are never shared (i.e. if it's only the wrapping ERTP asset, which can be validated) then this is fine. 

Anytime I receive an asset, it has methods that I can use to verify that the appropriate mint confirms that it validly addresses the set of rights (pixels, e.g.) that I'm expecting. I can then pull out the use rights in full confidence that color() will affect the correct pixels of the canvas I'm interested in.

**Comment by katelynsills** [comment]
The seatMint code was able to achieve this by allowing the minting code to associate a use object with the handle (id) in the extent of the ERTP payment

https://github.com/Agoric/ERTP/blob/27a3e27853f273f0e63dacf0827a45b26f757a6e/core/seatMint.js#L12-L17

**Comment by warner** [comment]
in the old repo. this was ERTP issue 104
