### ISSUE TITLE
Document chainmail in ERTP

### ISSUE THREAD

**Issue by Chris-Hibbert** [Agoric/ERTP#126]
There are a few .chainmail files [in ERTP](https://github.com/Agoric/ERTP/tree/master/core). We should add some doc (i.e. https://github.com/Agoric/ERTP/tree/master/Chainmail.md) saying what it is, how we hope to use it, and how to run the parser. 

Include references to the [literature](https://ai.google/research/pubs/pub44272).

**Comment by Chris-Hibbert** [comment]
related: https://github.com/Agoric/ERTP/issues/14

**Comment by katelynsills** [comment]
Closed by Agoric/ERTP#133

**Comment by warner** [comment]
in the old repo. this was ERTP issue 126
