### ISSUE TITLE
Common Pattern: getBalance() to get quantity

### ISSUE THREAD

**Issue by katelynsills** [Agoric/ERTP#141]
There's a common pattern of calling `getBalance()` which gives an amount, and then immediately getting the quantity. We may want to make this easier.

**Comment by erights** [comment]
I don't think so. Instead, we should make it easier and more pleasant to use amounts. "3 quatloos" and more meaningful than "3".

**Comment by katelynsills** [comment]
Good point. I'll close this

**Comment by warner** [comment]
in the old repo. this was ERTP issue 141
