### ISSUE TITLE
A name for the "smart contract agent"

### ISSUE THREAD

**Issue by DavidBruant** [Agoric/ERTP#220]
I have an internal train of thought that goes this way: i would like to call "InstanceInformation" a "contract", but the analogy with paper-contract is a bit lost because the source code is a better object for the "contract" analogy. But "installation" and "instance" feels a bit too object-oriented to me

[Building on the idea that the smart contract is an "actor" that can "own" digital assets](https://youtu.be/HaqXo74t5kI?t=1110), maybe a term is needed to name this concept; a concept that doesn't really have a good analogy in real life. Maybe it's simply "SmartContract", but maybe "smart contract" is already too loaded
Maybe "ContractActor" or "ContractAgent" or "AliveContract" or "RunningContract" or something else. 

What i'm looking for is a term that conveys the idea that what's created by the current `zoe.makeInstance` (or `contractHost.spawn`) is sort of its own thing, has an agency at the same "level" than humans interacting on the blockchain. "installation" and "instance" do not really capture this idea

**Comment by DavidBruant** [comment]
An option could have been "table" to follow up the "seat" analogy, but i'm not sure it works. When you play Poker with friends, the table does not "own" your money in the same way what's created by `zoe.makeInstance` does

**Comment by Chris-Hibbert** [comment]
I think, by analogy to Ethereum, that 'contract' works in this case. People dealing with Ethereum have gotten used to the idea that contracts control access to assets, have ownership of accounts, and can send payments to others. This may be a new idea in the conventional world, but it has become accepted terminology in the blockchain space.

**Comment by DavidBruant** [comment]
Even better! If there is already an accepted terminology in the blockchain space, then let's use it!

**Comment by katelynsills** [comment]
Yup, I would agree with Chris here. We can add an explanation of the concept that smart contracts can hold assets in case it is new to people, but I think the name 'smart contract' is good.

**Comment by katelynsills** [comment]
I'm closing this in favor of the issue on Agoric/documentation https://github.com/Agoric/documentation/issues/62

**Comment by warner** [comment]
in the old repo. this was ERTP issue 220
