### ISSUE TITLE
Use long-lived contract host in gallery tests

### ISSUE THREAD

**Issue by katelynsills** [Agoric/ERTP#45]
I realize this code hasn't changed in this PR, but why does sellToGallery() create a new contractHost on every sale? the contractHost is intended to be persistent and shared across many contracts and installations of contracts.

_Originally posted by @Chris-Hibbert in https://github.com/Agoric/ERTP/pull/36_

**Comment by katelynsills** [comment]
I have a local branch for this complete but won't submit a PR until the backlog of PRs goes down a bit.

**Comment by Chris-Hibbert** [comment]
That sounds perfect. It's certainly not urgent that it get in.

**Comment by warner** [comment]
in the old repo. this was ERTP issue 45
